// Basketball starting-lineup matcher (spec 025 US3) -- a TypeScript port of
// BasketballRules.prepareLineup / tryAssign (backend/.../sport/BasketballRules.java),
// generalized from the fixed nine-slot template to any `rosterPositions`.
//
// "Your team" and "fills a need" used to be a two-pass greedy keyed on the
// single (alphabetical-first) position, which cannot seat a PG/SG at SG and a
// later pure PG at PG. The backend's rule is a matroid greedy: sort by value
// (= ADP ascending), keep each player whose addition leaves the kept set
// matchable into distinct slots (Kuhn augmenting path), stop when every slot is
// taken. This file is that rule and nothing else.
//
// It is pinned to the backend by a cross-language parity fixture,
// web/src/__fixtures__/nba-lineup-parity.json, generated by
// NbaLineupParityFixtureTest from BasketballRules itself and replayed by
// lineup.parity.test.ts. If you change the matching here, that test is the
// judge; do not "fix" it by editing the fixture by hand.

import type { PlayerRef } from './api'
import { eligiblePositions } from './positions'

/**
 * Which positions each NBA roster slot accepts -- mirrors
 * BasketballRules.SLOT_ACCEPTS / isEligible. PG/SG/SF/PF/C are dedicated; G
 * accepts PG/SG, F accepts SF/PF, UTIL accepts any of the five. The one shared
 * copy: teamNeeds.ts reads it too rather than keeping its own.
 */
export const NBA_SLOT_ELIGIBILITY: Record<string, Set<string>> = {
  PG: new Set(['PG']),
  SG: new Set(['SG']),
  SF: new Set(['SF']),
  PF: new Set(['PF']),
  C: new Set(['C']),
  G: new Set(['PG', 'SG']),
  F: new Set(['SF', 'PF']),
  UTIL: new Set(['PG', 'SG', 'SF', 'PF', 'C']),
}

const NONE = new Set<string>()

function acceptsOf(slot: string): Set<string> {
  return NBA_SLOT_ELIGIBILITY[slot] ?? NONE // an unrecognized slot never seats anyone
}

function slotTakes(slot: string, positions: string[]): boolean {
  const a = acceptsOf(slot)
  return positions.some((p) => a.has(p))
}

export type Lineup = {
  /** Starting slots (BN/IR dropped), in template order. */
  slots: string[]
  /** Per slot: index into `kept`, or -1 when empty (BasketballRules' `assign`). */
  assign: number[]
  /** Seated players in the order the greedy kept them (ADP ascending, drafted order on ties). */
  kept: PlayerRef[]
  /** Per slot: the seated player or null. Derived from assign/kept. */
  seats: (PlayerRef | null)[]
}

function seatsOf(assign: number[], kept: PlayerRef[]): (PlayerRef | null)[] {
  return assign.map((i) => (i === -1 ? null : kept[i]))
}

/**
 * Port of BasketballRules.tryAssign. `keptPos[i]` is the eligible positions of
 * whichever kept player occupies index `i`; `placingPos` those of whoever we
 * are placing now (a kept player being bumped, or the original candidate).
 * Mutates `assign` ONLY on success, as the Java does, so a failed call leaves it
 * untouched -- callers pass a clone.
 */
function tryAssign(
  slots: string[],
  placingId: number,
  placingPos: string[],
  assign: number[],
  keptPos: string[][],
  seenSlot: boolean[],
): boolean {
  for (let s = 0; s < slots.length; s++) {
    if (!slotTakes(slots[s], placingPos) || seenSlot[s]) continue
    seenSlot[s] = true
    const occupant = assign[s]
    if (occupant === -1 || tryAssign(slots, occupant, keptPos[occupant], assign, keptPos, seenSlot)) {
      assign[s] = placingId
      return true
    }
  }
  return false
}

/**
 * BasketballRules.prepareLineup for a roster of `players` (drafted order) into
 * the starter slots of `rosterPositions`.
 *
 * Parity with the simulation only holds for ONE template: BasketballRules hard-codes
 * its slots as PG,SG,G,SF,PF,F,C,UTIL,UTIL and ignores the league's roster_positions.
 * This function reads `rosterPositions`, so for any other template (an extra UTIL, no
 * G/F, a different order) the lineup and "Fills X" here would diverge from what the
 * sim scores. All current NBA leagues use that template; the parity fixture covers
 * only it (spec 025 code review R3).
 */
export function seatLineup(rosterPositions: string[], players: PlayerRef[]): Lineup {
  const slots = rosterPositions.filter((s) => s !== 'BN' && s !== 'IR')
  // Java: List.sort by value descending, stable. value = exp(-adp/decay), so ADP
  // ascending; Array.prototype.sort is stable, so ties keep drafted order.
  const sorted = [...players].sort((a, b) => a.adp - b.adp)

  let assign: number[] = slots.map(() => -1)
  const kept: PlayerRef[] = []
  const keptPos: string[][] = []

  // Matroid greedy: keep each player whose addition leaves the kept set
  // matchable. Deliberately does NOT stop at the first player who does not fit
  // -- a lower-valued player later in `sorted` may still be matchable.
  for (const e of sorted) {
    if (kept.length === slots.length) break
    const pos = eligiblePositions(e, 'nba')
    if (pos.length === 0) continue // no recognized position; cannot occupy any slot
    const trial = assign.slice()
    const seen = slots.map(() => false)
    const newIdx = kept.length
    if (tryAssign(slots, newIdx, pos, trial, keptPos, seen)) {
      assign = trial
      kept.push(e)
      keptPos.push(pos)
    }
  }
  return { slots, assign, kept, seats: seatsOf(assign, kept) }
}

/**
 * A lineup rebuilt from an already-seated slot list (computeTeamNeeds' output),
 * so a caller holding only SlotStatus[] can still ask canJoin. The Kuhn search
 * needs nothing but the assignment and each seated player's positions.
 */
export function lineupFromSeats(slots: string[], seats: (PlayerRef | null)[]): Lineup {
  const kept: PlayerRef[] = []
  const assign = seats.map((p) => {
    if (p == null) return -1
    kept.push(p)
    return kept.length - 1
  })
  return { slots, assign, kept, seats: seats.slice() }
}

export type CanJoin = { ok: boolean; slot: string | null; index: number }

/**
 * BasketballRules' maskCanJoin for one candidate: can he be added to the
 * starting nine, possibly by shifting seated players between slots?
 *
 * `slot` is what the UI names ("Fills X"). DEFINITION (code-review B1; this
 * supersedes research A1's "an open slot he is directly eligible for, dedicated
 * first" heuristic): it is the slot that goes from OPEN to FILLED when
 * seatLineup is re-run with the candidate appended -- the very lineup the team
 * strip shows after the pick. A "directly eligible" open slot is wrong because
 * the re-run's Kuhn walk often seats the newcomer in a filled slot and shifts
 * its occupant into a DIFFERENT open slot, so the tag would name a slot the
 * strip still shows open. By construction the tag, the card's "still open"
 * list and the strip agree, and it is never a filled slot.
 * `index` is that slot's index in lineup.slots (what fitSlot numbers by).
 *
 * Caveat: the re-run is over the SEATED players (lineup.kept) plus the
 * candidate. That equals the full-roster re-run (benched players are in the
 * span of earlier-kept ones in a matroid greedy), except possibly on exact-ADP
 * ties among seated players, whose drafted order is not recoverable here.
 */
export function canJoin(lineup: Lineup, player: PlayerRef): CanJoin {
  const no: CanJoin = { ok: false, slot: null, index: -1 }
  const pos = eligiblePositions(player, 'nba')
  if (pos.length === 0) return no
  const { slots, assign, kept } = lineup
  const keptPos = kept.map((k) => eligiblePositions(k, 'nba'))
  const trial = assign.slice()
  const seen = slots.map(() => false)
  if (!tryAssign(slots, kept.length, pos, trial, keptPos, seen)) return no

  // He is joinable, so the re-run keeps everyone plus him (matroid greedy).
  const after = seatLineup(slots, [...kept, player])
  const idx = slots.findIndex((_, i) => assign[i] === -1 && after.assign[i] !== -1)
  if (idx === -1) return no // unreachable: a joinable candidate fills a previously empty slot
  return { ok: true, slot: slots[idx], index: idx }
}
