import { describe, expect, it } from 'vitest'
import type { PlayerRef } from './api'
import { canJoin, seatLineup } from './lineup'
import fixture from './__fixtures__/nba-lineup-parity.json'

/**
 * Cross-language parity (spec 025 T018): replays every case of
 * __fixtures__/nba-lineup-parity.json -- generated by the backend's
 * NbaLineupParityFixtureTest from BasketballRules itself -- through the
 * TypeScript port and demands identical answers: who is seated (in greedy
 * order), who sits in which template slot, how many slots of each kind are
 * filled, and which of the 32 eligibility masks could still join.
 */

type FxPlayer = { id: number; positions: string[]; adp: number }
type FxCase = {
  name: string
  players: FxPlayer[]
  seated: number[]
  seating: (number | null)[]
  filledByKind: Record<string, number>
  canJoinByMask: boolean[]
}
const fx = fixture as { template: string[]; cases: FxCase[] }

// PG=1, SG=2, SF=4, PF=8, C=16 -- BasketballRules.POSITION_BIT order.
const BITS = ['PG', 'SG', 'SF', 'PF', 'C']

function ref(p: FxPlayer): PlayerRef {
  return {
    id: p.id,
    sleeperId: String(p.id),
    name: `P${p.id}`,
    position: p.positions[0] as PlayerRef['position'],
    positions: p.positions as PlayerRef['positions'],
    team: null,
    adp: p.adp,
    positionalRank: 1,
  }
}

function probe(mask: number): PlayerRef {
  const positions = BITS.filter((_, b) => (mask & (1 << b)) !== 0)
  return ref({ id: 900000 + mask, positions, adp: 9999 })
}

describe('TypeScript lineup port matches BasketballRules on the parity fixture', () => {
  it('the fixture has the real template and at least 20 cases', () => {
    expect(fx.template).toEqual(['PG', 'SG', 'G', 'SF', 'PF', 'F', 'C', 'UTIL', 'UTIL'])
    expect(fx.cases.length).toBeGreaterThanOrEqual(20)
  })

  for (const c of fx.cases) {
    describe(c.name, () => {
      const lineup = seatLineup([...fx.template, 'BN', 'BN', 'BN', 'BN', 'BN'], c.players.map(ref))

      it('seats the same players in the same (kept) order', () => {
        expect(lineup.kept.map((p) => p.id)).toEqual(c.seated)
      })

      it('puts each player in the same template slot', () => {
        expect(lineup.seats.map((p) => (p ? p.id : null))).toEqual(c.seating)
      })

      it('fills the same number of slots of each kind', () => {
        const filled: Record<string, number> = {}
        lineup.slots.forEach((slot, i) => {
          if (lineup.seats[i]) filled[slot] = (filled[slot] ?? 0) + 1
        })
        expect(filled).toEqual(c.filledByKind)
      })

      it('agrees on which of the 32 eligibility masks can still join', () => {
        const got = Array.from({ length: 32 }, (_, m) => canJoin(lineup, probe(m)).ok)
        expect(got).toEqual(c.canJoinByMask)
      })

      it('names an OPEN slot the probe is joinable into, never a filled one (A1)', () => {
        for (let m = 1; m < 32; m++) {
          const r = canJoin(lineup, probe(m))
          if (!r.ok) {
            expect(r.slot).toBeNull()
            continue
          }
          expect(lineup.seats[r.index]).toBeNull()
          expect(lineup.slots[r.index]).toBe(r.slot)
        }
      })
    })
  }
})

describe('canJoin names the slot (research A1)', () => {
  const T = ['PG', 'SG', 'G', 'SF', 'PF', 'F', 'C', 'UTIL', 'UTIL', 'BN']
  it('a second C with C filled and UTIL open reads UTIL, not C', () => {
    const lineup = seatLineup(T, [ref({ id: 1, positions: ['C'], adp: 3 })])
    expect(canJoin(lineup, ref({ id: 2, positions: ['C'], adp: 12 }))).toMatchObject({ ok: true, slot: 'UTIL' })
  })

  it('prefers the dedicated slot, then G over UTIL', () => {
    const empty = seatLineup(T, [])
    expect(canJoin(empty, ref({ id: 1, positions: ['PG', 'SG'], adp: 5 })).slot).toBe('PG')
    const pgTaken = seatLineup(T, [ref({ id: 1, positions: ['PG'], adp: 3 })])
    expect(canJoin(pgTaken, ref({ id: 2, positions: ['PG'], adp: 9 })).slot).toBe('G')
  })

  it('when joining needs a shift, names the open slot the shift fills', () => {
    // PG/SG at PG, SG filled by a pure SG? Build: PG/SG seated at PG, G-eligible only
    // slots left for a pure PG: dedicated PG is taken, G is open and directly eligible.
    // Force a true shift: template PG,SG only, PG/SG seated at PG; a pure PG joins by
    // moving PG/SG to SG, so the open slot filled is SG.
    const lineup = seatLineup(['PG', 'SG'], [ref({ id: 1, positions: ['PG', 'SG'], adp: 3 })])
    expect(lineup.seats[0]?.id).toBe(1)
    expect(canJoin(lineup, ref({ id: 2, positions: ['PG'], adp: 9 }))).toMatchObject({ ok: true, slot: 'SG' })
  })

  it('cannot join when no augmentation exists', () => {
    const lineup = seatLineup(['C'], [ref({ id: 1, positions: ['C'], adp: 3 })])
    expect(canJoin(lineup, ref({ id: 2, positions: ['C'], adp: 9 }))).toMatchObject({ ok: false, slot: null })
  })

  it('seats a PG/SG then a pure PG both (the counterexample the old greedy failed)', () => {
    const lineup = seatLineup(T, [
      ref({ id: 1, positions: ['PG', 'SG'], adp: 5 }),
      ref({ id: 2, positions: ['PG'], adp: 20 }),
    ])
    expect(lineup.kept.map((p) => p.id)).toEqual([1, 2])
  })
})
